[package]
name = "nitidus-ui-kit"
description = "Theme, layout, and widget toolkit for nitidus"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy.workspace = true
plurimus.workspace = true
ratatui.workspace = true

[lints]
workspace = true
