[package]
name = "nitidus"
description = "A TUI email client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bevy.workspace = true
bevy_ratatui.workspace = true
etcetera.workspace = true
nitidus-ui-kit.workspace = true
plurimus.workspace = true
ratatui.workspace = true
tachyonfx.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
